name: Java CI with Gradle

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: gradle/wrapper-validation-action@v1
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: build bootBuildImage --scan
      - uses: actions/upload-artifact@v3
        with:
          path: build/libs/spring-boot-demo-0.0.1-SNAPSHOT.jar

